"""init

Revision ID: d578c87b3416
Revises: a6c3ee6bc23f
Create Date: 2024-03-07 16:10:26.498418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd578c87b3416'
down_revision: Union[str, None] = 'a6c3ee6bc23f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('locale', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'locale')
    # ### end Alembic commands ###
